# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20150508_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultset',
            name='p10q1',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p10q10',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p10q11',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p10q12',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p10q2',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p10q3',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p10q4',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p10q5',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p10q6',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p10q7',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p10q8',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p10q9',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p11q1',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p11q10',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p11q11',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p11q12',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p11q13',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p11q14',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p11q2',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p11q3',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p11q4',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p11q5',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p11q6',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p11q7',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p11q8',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p11q9',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p1q1',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p1q10',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p1q11',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p1q2',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p1q3',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p1q4',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p1q5',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p1q6',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p1q7',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p1q8',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p1q9',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p2q1',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p2q10',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p2q11',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p2q2',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p2q3',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p2q4',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p2q5',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p2q6',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p2q7',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p2q8',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p2q9',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p3q1',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p3q2',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p3q3',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p3q4',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p3q5',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p3q6',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p3q7',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p3q8',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p3q9',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p4q1',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p4q10',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p4q11',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p4q2',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p4q3',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p4q4',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p4q5',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p4q6',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p4q7',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p4q8',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p4q9',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p5q1',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p5q10',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p5q11',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p5q12',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p5q13',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p5q14',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p5q2',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p5q3',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p5q4',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p5q5',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p5q6',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p5q7',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p5q8',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p5q9',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p6q1',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p6q10',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p6q11',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p6q12',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p6q2',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p6q3',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p6q4',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p6q5',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p6q6',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p6q7',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p6q8',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p6q9',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p7q1',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p7q2',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p7q3',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p7q4',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p7q5',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p7q6',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p7q7',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p7q8',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p7q9',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p8q1',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p8q10',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p8q11',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p8q12',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p8q2',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p8q3',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p8q4',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p8q5',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p8q6',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p8q7',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p8q8',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p8q9',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p9q1',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p9q10',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p9q11',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p9q12',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p9q13',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p9q2',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p9q3',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p9q4',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p9q5',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p9q6',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p9q7',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p9q8',
        ),
        migrations.RemoveField(
            model_name='resultset',
            name='p9q9',
        ),
        migrations.AddField(
            model_name='resultset',
            name='p1',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='resultset',
            name='p10',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='resultset',
            name='p11',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='resultset',
            name='p2',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='resultset',
            name='p3',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='resultset',
            name='p4',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='resultset',
            name='p5',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='resultset',
            name='p6',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='resultset',
            name='p7',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='resultset',
            name='p8',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='resultset',
            name='p9',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
