# -*- coding: utf-8 -*-
choices_1 = {
  'q1': (
    ('freshman', 'Freshman'),
    ('sophomore', 'Sophomore'),
    ('junior', 'Junior'),
    ('senior', 'Senior'),
    ('master', 'Master'),
    ('doctorate', 'Doctorate'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q2': (
    ('', '--------'),
    ('other', 'Something Else'),
    ('undecided', 'Undecided'),
    ('nocomment', 'No Comment'),
    ('', '--------'),
    ('accounting', 'Accounting'),
    ('aerospaceengineering', 'Aerospace Engineering'),
    ('agribusiness', 'Agribusiness'),
    ('agriengineering', 'Agricultural Engineering Technology and Business'),
    ('agriinformation', 'Agricultural Information Science'),
    ('agriculture', 'Agricultural Science'),
    ('agronomy', 'Agronomy'),
    ('dairyscience', 'Animal and Dairy Science'),
    ('anthropology', 'Anthropology'),
    ('architecture', 'Architecture'),
    ('art', 'Art'),
    ('biochemistry', 'Biochemistry'),
    ('bioengineering', 'Biological Engineering'),
    ('biology', 'Biological Sciences'),
    ('building', 'Building Construction Science'),
    ('businessadmin', 'Business Administration'),
    ('businessecon', 'Business Economics'),
    ('businessinfo', 'Business Information Systems'),
    ('chemengineering', 'Chemical Engineering'),
    ('chemistry', 'Chemistry'),
    ('civilengineering', 'Civil Engineering'),
    ('communication', 'Communication'),
    ('computerengineering', 'Computer Engineering'),
    ('computerscience', 'Computer Science'),
    ('criminology', 'Criminology'),
    ('culinology', 'Culinology'),
    ('economics', 'Economics Major (Arts and Sciences)'),
    ('educationalpsyc', 'Educational Psychology'),
    ('electricalengineering', 'Electrical Engineering'),
    ('elementaryed', 'Elementary Education'),
    ('english', 'English'),
    ('enviromentalecon', 'Environmental Economics and Management'),
    ('finance', 'Finance'),
    ('foodscience', 'Food Science, Nutrition and Health Promotion'),
    ('foreignlanguage', 'Foreign Language'),
    ('forestry', 'Forestry'),
    ('generallibarts', 'General Liberal Arts'),
    ('generalscience', 'General Science'),
    ('geoscience', 'Geosciences'),
    ('history', 'History'),
    ('horticulture', 'Horticulture'),
    ('humanscience', 'Human Sciences'),
    ('industrialengineering', 'Industrial Engineering'),
    ('industrialtech', 'Industrial Technology'),
    ('informationtech', 'Information Technology Services'),
    ('interdisciplinary', 'Interdisciplinary Studies'),
    ('interiordesign', 'Interior Design'),
    ('kinesiology', 'Kinesiology'),
    ('landscapearchitecture', 'Landscape Architecture'),
    ('landscapecontracting', 'Landscape Contracting'),
    ('management', 'Management'),
    ('marketing', 'Marketing'),
    ('mathematics', 'Mathematics'),
    ('mechanicalengineering', 'Mechanical Engineering'),
    ('medicaltech', 'Medical Technology'),
    ('microbiology', 'Microbiology'),
    ('musiceducation', 'Music Education'),
    ('music', 'Music'),
    ('philosophy', 'Philosophy'),
    ('physics', 'Physics'),
    ('polyscience', 'Political Science'),
    ('pultryscience', 'Poultry Science'),
    ('psychology', 'Psychology'),
    ('secondaryeducation', 'Secondary Education'),
    ('socialwork', 'Social Work'),
    ('sociology', 'Sociology'),
    ('softwareengineering', 'Software Engineering'),
    ('specialeducation', 'Special Education'),
    ('techteachereducation', 'Technology Teacher Education'),
    ('veterinarymedical', 'Veterinary Medical Technology'),
    ('wildlife', 'Wildlife, Fisheries and Aquaculture'),
  ),
  'q3': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q4': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q5': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q6': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('nocomment', 'No Comment'),
  ),
  'q7': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notavailable', 'None were avaliable'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q8': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q9': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q10': (
    ('strongdisagree', 'Strongly Disagree'),
    ('disagree', 'Disagree'),
    ('neutral', 'Neither Agree nor Disagree'),
    ('agree', 'Agree'),
    ('strongagree', 'Strongly Agree'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No comment'),
  ),
  'q11': (
    ('parent', 'Parent(s)'),
    ('grandparent', 'Grandparents'),
    ('sibling', 'Siblings'),
    ('auntuncle', 'Aunts or Uncles'),
    ('familyfriend', 'Family friends'),
    ('peer', 'Peers'),
    ('teammate', 'Teammates'),
    ('teacher', 'Teacher'),
    ('coach', 'Coach'),
    ('signother', 'Significant Other'),
    ('family', 'Family'),
    ('none', 'None of these'),
    ('notsure', 'Not sure'),
    ('nocomment', 'No comment'),
  )
}

choices_2 = {
  'q1': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q2': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q3': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q4': (
    ('poor', '1 (poor)'),
    ('belowaverage', '2'),
    ('average', '3'),
    ('aboveaverage', '4'),
    ('excellent', '5 (excellent)'),
  ),
  'q5': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q6': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q7': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q8': (
    ('visual', 'Visual (Seeing)'),
    ('auditory', 'Auditory (Hearing)'),
    ('kinsethetics', 'Kinesthetics (Hands-on)'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  )
}

choices_3 = {
  'q1': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q3': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q4': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q5': (
    ('decressed', 'Decreased '),
    ('increased', 'Increased'),
    ('same', 'Stayed the same'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q6': (
    ('never', 'Never'),
    ('rarely', 'Rarely'),
    ('some', 'Some'),
    ('often', 'Often'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q7': (
    ('never', 'Never'),
    ('rarely', 'Rarely'),
    ('some', 'Some'),
    ('often', 'Often'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q8': (
    ('never', 'Never'),
    ('rarely', 'Rarely'),
    ('some', 'Some'),
    ('often', 'Often'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q9': (
    ('never', 'Never'),
    ('rarely', 'Rarely'),
    ('some', 'Some'),
    ('often', 'Often'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
}

choices_4 = {
  'q1': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q2': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q3': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q4': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q5': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q6': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q7': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q8': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q9': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q10': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q11': (
    ('front','Near the front'),
    ('middle','Middle'),
    ('back','Near the back'),
    ('notsure','Not Sure'),
    ('nocomment','No comment'),
  )
}

choices_5 = {
  'q1': (
    ('notimportant', 'Not At All Important'),
    ('someimportant', 'Somewhat Important'),
    ('important', 'Important'),
    ('veryimportant', 'Very Important'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q2': (
    ('notimportant', 'Not At All Important'),
    ('someimportant', 'Somewhat Important'),
    ('important', 'Important'),
    ('veryimportant', 'Very Important'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q3': (
    ('notimportant', 'Not At All Important'),
    ('someimportant', 'Somewhat Important'),
    ('important', 'Important'),
    ('veryimportant', 'Very Important'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q4': (
    ('notimportant', 'Not At All Important'),
    ('someimportant', 'Somewhat Important'),
    ('important', 'Important'),
    ('veryimportant', 'Very Important'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q5': (
    ('notimportant', 'Not At All Important'),
    ('someimportant', 'Somewhat Important'),
    ('important', 'Important'),
    ('veryimportant', 'Very Important'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q6': (
    ('notimportant', 'Not At All Important'),
    ('someimportant', 'Somewhat Important'),
    ('important', 'Important'),
    ('veryimportant', 'Very Important'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q7': (
    ('notimportant', 'Not At All Important'),
    ('someimportant', 'Somewhat Important'),
    ('important', 'Important'),
    ('veryimportant', 'Very Important'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q8': (
    ('notimportant', 'Not At All Important'),
    ('someimportant', 'Somewhat Important'),
    ('important', 'Important'),
    ('veryimportant', 'Very Important'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q9': (
    ('notimportant', 'Not At All Important'),
    ('someimportant', 'Somewhat Important'),
    ('important', 'Important'),
    ('veryimportant', 'Very Important'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q10': (
    ('notimportant', 'Not At All Important'),
    ('someimportant', 'Somewhat Important'),
    ('important', 'Important'),
    ('veryimportant', 'Very Important'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q11': (
    ('notimportant', 'Not At All Important'),
    ('someimportant', 'Somewhat Important'),
    ('important', 'Important'),
    ('veryimportant', 'Very Important'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q12': (
    ('notimportant', 'Not At All Important'),
    ('someimportant', 'Somewhat Important'),
    ('important', 'Important'),
    ('veryimportant', 'Very Important'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q13': (
    ('notimportant', 'Not At All Important'),
    ('someimportant', 'Somewhat Important'),
    ('important', 'Important'),
    ('veryimportant', 'Very Important'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q14': (
    ('notimportant', 'Not At All Important'),
    ('someimportant', 'Somewhat Important'),
    ('important', 'Important'),
    ('veryimportant', 'Very Important'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  )
}

choices_6 = {
  'q1': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q2': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q3': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q4': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q5': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q6': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q7': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q8': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q9': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q10': (
    ('strongdisagree', 'Strongly Disagree'),
    ('disagree', 'Disagree'),
    ('neutral', 'Neither Agree nor Disagree'),
    ('agree', 'Agree'),
    ('strongagree', 'Strongly Agree'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No comment'),
  ),
  'q11': (
    ('strongdisagree', 'Strongly Disagree'),
    ('disagree', 'Disagree'),
    ('neutral', 'Neither Agree nor Disagree'),
    ('agree', 'Agree'),
    ('strongagree', 'Strongly Agree'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No comment'),
  ),
  'q12': (
    ('strongdisagree', 'Strongly Disagree'),
    ('disagree', 'Disagree'),
    ('neutral', 'Neither Agree nor Disagree'),
    ('agree', 'Agree'),
    ('strongagree', 'Strongly Agree'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No comment'),
  )
}

choices_7 = {
  'q1': (
    ('a','A'),
    ('b','B'),
    ('c','C'),
    ('d','D'),
    ('f','F'),
    ('notsure','Not Sure'),
    ('nocomment','No Comment'),
    ('notapplicable', 'N/A')
  ),
  'q2': (
    ('a','A'),
    ('b','B'),
    ('c','C'),
    ('d','D'),
    ('f','F'),
    ('notsure','Not Sure'),
    ('nocomment','No Comment'),
    ('notapplicable', 'N/A')
  ),
  'q3': (
    ('a','A'),
    ('b','B'),
    ('c','C'),
    ('d','D'),
    ('f','F'),
    ('notsure','Not Sure'),
    ('nocomment','No Comment'),
    ('notapplicable', 'N/A')
  ),
  'q4': (
    ('a','A'),
    ('b','B'),
    ('c','C'),
    ('d','D'),
    ('f','F'),
    ('notsure','Not Sure'),
    ('nocomment','No Comment'),
    ('notapplicable', 'N/A')
  ),
  'q5': (
    ('a','A'),
    ('b','B'),
    ('c','C'),
    ('d','D'),
    ('f','F'),
    ('notsure','Not Sure'),
    ('nocomment','No Comment'),
    ('notapplicable', 'N/A')
  ),
}

choices_8 = {
  'q1': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q2': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q3': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q4': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q5': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q6': (
    ('strongdisagree', 'Strongly Disagree'),
    ('disagree', 'Disagree'),
    ('neutral', 'Neither Agree nor Disagree'),
    ('agree', 'Agree'),
    ('strongagree', 'Strongly Agree'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No comment'),
  ),
  'q7': (
    ('strongdisagree', 'Strongly Disagree'),
    ('disagree', 'Disagree'),
    ('neutral', 'Neither Agree nor Disagree'),
    ('agree', 'Agree'),
    ('strongagree', 'Strongly Agree'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No comment'),
  ),
  'q8': (
    ('strongdisagree', 'Strongly Disagree'),
    ('disagree', 'Disagree'),
    ('neutral', 'Neither Agree nor Disagree'),
    ('agree', 'Agree'),
    ('strongagree', 'Strongly Agree'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No comment'),
  ),
  'q9': (
    ('strongdisagree', 'Strongly Disagree'),
    ('disagree', 'Disagree'),
    ('neutral', 'Neither Agree nor Disagree'),
    ('agree', 'Agree'),
    ('strongagree', 'Strongly Agree'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No comment'),
  ),
  'q10': (
    ('strongdisagree', 'Strongly Disagree'),
    ('disagree', 'Disagree'),
    ('neutral', 'Neither Agree nor Disagree'),
    ('agree', 'Agree'),
    ('strongagree', 'Strongly Agree'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No comment'),
  ),
  'q11': (
    ('strongdisagree', 'Strongly Disagree'),
    ('disagree', 'Disagree'),
    ('neutral', 'Neither Agree nor Disagree'),
    ('agree', 'Agree'),
    ('strongagree', 'Strongly Agree'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No comment'),
  ),
  'q12': (
    ('strongdisagree', 'Strongly Disagree'),
    ('disagree', 'Disagree'),
    ('neutral', 'Neither Agree nor Disagree'),
    ('agree', 'Agree'),
    ('strongagree', 'Strongly Agree'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No comment'),
  ),
}

choices_9 = {
  'q1': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q3': (
    ('oncampus', 'On Campus'),
    ('offcampus', 'Off Campus'),
    ('nocomment', 'No Comment'),
  ),
  'q4': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q7': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
}

choices_10 = {}

choices_11 = {
  'q2': (
    ('female', 'Female'),
    ('male', 'Male'),
    ('nocomment', 'No Comment'),
  ),
  'q3': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('nocomment', 'No Comment'),
  ),
  'q4': (
    ('oncampus', 'On Campus'),
    ('offcampus', 'Off Campus'),
    ('nocomment', 'No Comment'),
  ),
  'q6': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('nocomment', 'No Comment'),
  ),
  'q7': (
    ('none','No formal education'),
    ('somehighschool','Some High School or less'),
    ('highschool','High School Diploma or GED'),
    ('somecollege','Some college, did not complete degree'),
    ('associate','Associate Degree'),
    ('bachelor','Bachelor\'s Degree (B.S., B.A.)'),
    ('master','Master\'s Degree (M.S., M.A)'),
    ('professional','Professional Degree (MD, JD, EdD, PsyD, ect.)'),
    ('doctorate','Doctorate Degree (Ph.D.)'),
    ('notsure','Not Sure'),
    ('nodcomment','No comment'),
  ),
  'q8': (
    ('none','No formal education'),
    ('somehighschool','Some High School or less'),
    ('highschool','High School Diploma or GED'),
    ('somecollege','Some college, did not complete degree'),
    ('associate','Associate Degree'),
    ('bachelor','Bachelor\'s Degree (B.S., B.A.)'),
    ('master','Master\'s Degree (M.S., M.A)'),
    ('professional','Professional Degree (MD, JD, EdD, PsyD, ect.)'),
    ('doctorate','Doctorate Degree (Ph.D.)'),
    ('notsure','Not Sure'),
    ('nodcomment','No comment'),
  ),
  'q9': (
    ('black', 'Majority Black'),
    ('white', 'Majority White'),
    ('neutral', 'About Equal'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No comment'),
  ),
  'q10': (
    ('black', 'African American'),
    ('white', 'White/ Caucasian'),
    ('asian', 'Asian American'),
    ('hispanic', 'Hispanic/Latino'),
    ('native', 'Native American'),
    ('pasific', 'Pacific Islander'),
    ('multi', 'Multi-racial'),
    ('nocomment', 'No comment'),
  ),
  'q11': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q12': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q13': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
  'q14': (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('notsure', 'Not Sure'),
    ('nocomment', 'No Comment'),
  ),
}